### PR TITLE
refactor some areas

### PR DESCRIPTION
**Pull request by secondl1ght**
I just refactored a few things with the code but kept your changes, thanks for the PR! :)

### CODE REVIEW

**Comment by michaelWuensch** [comment]
Everything is nice and more clean then my changes.
There is one small issue though.
When switching between a page that has the normal header and one where the title is flipped, it looks like the whole header jumps about 2 units. 
For example the "Contribute to" is higher then the BitBanana text from Docs.
That is actually why I changed the space-y from 16 to 14 in then added top padding of 2 in h2 tag in that extra template.
That kinda fixed it without causing the body text to move as well. Maybe you have a more elegant solution for this.

**Comment by secondl1ght** [comment]
Ohh ok, I was wondering why you had that there. That is some serious attention to detail haha. The `space-y-16` won't affect this because that is setting the spacing between the header, copy, and button which is the same whether the header text is on top or bottom of the image. I will add back in the `pt-2` even though it is a bit weird and we can set the spacing back to 16 if we want or leave it as is, 16 is used in other parts of the site so it would be more consistent in that regard.

**Comment by michaelWuensch** [comment]
Haha, yes, I am a perfectionist....
Now that you readded it, the copy text jumps. You will more easily notice that when you use a bigger value than 2. When there is no easy way to fix it, then I would actually rater go with the header jumping and go back to space-y to 16.

**Comment by secondl1ght** [comment]
Ok I have reverted those changes, I think this is the best option imo.

**Pull request merged**
